plugins {
	java
	id("org.springframework.boot") version "4.0.5"
	id("io.spring.dependency-management") version "1.1.7"
	id("org.openapi.generator") version "7.21.0"
}

group = "io.two.bit.saint"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom(configurations.annotationProcessor.get())
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-webmvc")
	compileOnly("org.projectlombok:lombok")
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	runtimeOnly("com.mysql:mysql-connector-j")
	annotationProcessor("org.projectlombok:lombok")
	testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")
	testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")

	// Swagger UI & OpenAPI 3 Support
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5")

	// Necessary for the code generated by the plugin
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("org.openapitools:jackson-databind-nullable:0.2.6")
	implementation("io.swagger.core.v3:swagger-annotations:2.2.20")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

openApiGenerate {
	generatorName.set("spring")
	inputSpec.set("$projectDir/src/main/resources/openapi/shunya-spec.yaml")
	outputDir.set("$buildDir/generated")
	configOptions.set(mapOf(
		"interfaceOnly" to "true",         // Generates only the interfaces
		"delegatePattern" to "true",      // CRITICAL: Generates the Delegate interface
		"skipDefaultInterface" to "false", // Ensures methods have default implementations
		"useSpringBoot3" to "true",
		"useTags" to "true",
		"ResponseEntity" to "true"        // Ensures return types are Wrapped in ResponseEntity
	))
}

// Add the generated code to your project's source set
sourceSets {
	main {
		java {
			srcDir("${buildDir}/generated-sources/src/main/java")
		}
	}
}

// Ensure code is generated before compiling
tasks.compileJava {
	dependsOn(tasks.openApiGenerate)
}
